Add missing return statement at end of unifycr_mount
This fixes the following compiler warning:

unifycr.c(2038): error #1011: missing return statement at end of
non-void function "unifycr_unmount"
  }
  ^

Correct unnecessary line break in same function.